# Generated by Django 4.2.4 on 2024-04-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
