# Generated by Django 5.0.4 on 2024-04-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
