# Generated by Django 5.0.4 on 2024-04-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0013_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
