# Generated by Django 5.0.4 on 2024-04-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0014_userprofile_removed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='removed',
            new_name='remove',
        ),
    ]
